"""
src/pdf_export.py
PDF chart export — 2-page layout.
Session 168 (Audit XIX-B).

Page 1: SVG chart + Panchanga + Basic positions table
Page 2: House scores + Active yogas + Current dasha

Uses weasyprint (HTML→PDF) if available; falls back to reportlab.
Source: Standard professional Jyotish consultation deliverable format.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional
import os
import datetime

_SIGN_NAMES = [
    "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
    "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces",
]

_PLANET_NAMES = ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu"]


def _chart_html(chart, chart_svg: str, panchanga=None, title: str = "Birth Chart") -> str:
    """Generate Page 1 HTML — chart + panchanga + positions."""

    # Planet positions table
    positions_rows = ""
    for p in _PLANET_NAMES:
        if p not in chart.planets:
            continue
        pd = chart.planets[p]
        lon = pd.longitude
        si  = pd.sign_index
        deg = getattr(pd, 'degree_in_sign', lon % 30)
        rx  = "℞" if getattr(pd, 'is_retrograde', False) else ""
        positions_rows += f"""
        <tr>
          <td><b>{p}</b></td>
          <td>{_SIGN_NAMES[si]}</td>
          <td>{deg:.2f}°</td>
          <td>{lon:.4f}°</td>
          <td>{rx}</td>
        </tr>"""

    # Panchanga section
    panch_html = ""
    if panchanga:
        panch_html = f"""
        <div class="panchanga">
          <h3>Panchanga</h3>
          <table>
            <tr><td><b>Tithi</b></td><td>{getattr(panchanga,'tithi_name','—')}</td>
                <td><b>Vara</b></td><td>{getattr(panchanga,'vara','—')}</td></tr>
            <tr><td><b>Nakshatra</b></td><td>{getattr(panchanga,'nakshatra','—')}</td>
                <td><b>Yoga</b></td><td>{getattr(panchanga,'yoga_name','—')}</td></tr>
            <tr><td><b>Karana</b></td><td>{getattr(panchanga,'karana','—')}</td>
                <td><b>Hora</b></td><td>{getattr(panchanga,'hora_lord','—')}</td></tr>
          </table>
        </div>"""

    lagna_si = chart.lagna_sign_index
    lagna_deg = chart.lagna % 30

    return f"""<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Georgia', serif; margin: 20px; font-size: 11pt; color: #1a1a1a; }}
  h1 {{ color: #7B1E2A; font-size: 18pt; text-align: center; margin-bottom: 4px; }}
  h2 {{ color: #D4500A; font-size: 14pt; border-bottom: 2px solid #D4500A; padding-bottom: 4px; }}
  h3 {{ color: #7B1E2A; font-size: 12pt; }}
  .header {{ text-align: center; margin-bottom: 16px; color: #595959; font-size: 10pt; }}
  .chart-svg {{ text-align: center; margin: 10px 0; }}
  table {{ width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 10pt; }}
  th {{ background: #1F3864; color: white; padding: 5px 8px; text-align: left; }}
  td {{ padding: 4px 8px; border-bottom: 1px solid #e0e0e0; }}
  tr:nth-child(even) td {{ background: #F5F0EB; }}
  .panchanga {{ margin: 10px 0; padding: 10px; background: #FFFEF5; border: 1px solid #D4500A; border-radius: 4px; }}
  .two-col {{ display: flex; gap: 20px; }}
  .col {{ flex: 1; }}
  .lagna-box {{ background: #FFF0D0; padding: 8px 12px; border: 1px solid #8B4513;
                border-radius: 4px; margin: 8px 0; font-size: 11pt; }}
  .footer {{ text-align: center; color: #888; font-size: 9pt; margin-top: 20px;
             border-top: 1px solid #ddd; padding-top: 8px; }}
</style>
</head><body>
<h1>ॐ — {title}</h1>
<div class="header">Generated by LagnaMaster v3.0.0 · {datetime.date.today().strftime('%d %B %Y')}</div>

<div class="lagna-box">
  <b>Lagna (Ascendant):</b> {_SIGN_NAMES[lagna_si]} {lagna_deg:.2f}°
  &nbsp;&nbsp;&nbsp;
  <b>Ayanamsha:</b> {getattr(chart, 'ayanamsha_name', 'Lahiri')}
</div>

<div class="two-col">
  <div class="col">
    <div class="chart-svg">{chart_svg}</div>
  </div>
  <div class="col">
    {panch_html}
    <h3>Planetary Positions</h3>
    <table>
      <tr><th>Planet</th><th>Sign</th><th>Degree</th><th>Longitude</th><th>Rx</th></tr>
      {positions_rows}
    </table>
  </div>
</div>

<div class="footer">
  LagnaMaster — Vedic Astrology Engine · Classical calculations per BPHS (PVRNR)
  · Scoring is a heuristic estimate, not an authoritative classical verdict.
</div>
</body></html>"""


def _analysis_html(chart, house_scores: dict = None, yogas: list = None,
                   dasha_info: dict = None, title: str = "") -> str:
    """Generate Page 2 HTML — scores + yogas + dasha."""

    # House scores table
    score_rows = ""
    if house_scores:
        score_labels = {
            range(8, 11): "Excellent", range(5, 8): "Strong", range(2, 5): "Good",
            range(-1, 2): "Neutral", range(-4, -1): "Weak", range(-11, -4): "Challenged"
        }
        for h in range(1, 13):
            s = house_scores.get(h, 0.0)
            label = "Neutral"
            for r, l in score_labels.items():
                if s in r or (s >= r.start and s < r.stop):
                    label = l; break
            bar_w = int((s + 10) / 20 * 120)
            bar_color = "#27AE60" if s >= 0 else "#E74C3C"
            score_rows += f"""
            <tr>
              <td>H{h}</td>
              <td>{s:+.2f}</td>
              <td>{label}</td>
              <td><div style="width:{bar_w}px;height:10px;background:{bar_color};border-radius:2px;"></div></td>
            </tr>"""

    # Yogas
    yoga_rows = ""
    if yogas:
        for y in yogas[:20]:  # cap at 20
            name = getattr(y, 'name', str(y))
            desc = getattr(y, 'description', '')[:80]
            strength = getattr(getattr(y, 'strength', None), 'strength_label', '—')
            yoga_rows += f"<tr><td><b>{name}</b></td><td>{strength}</td><td>{desc}</td></tr>"

    # Dasha
    dasha_html = ""
    if dasha_info:
        md = dasha_info.get('md_lord', '—')
        ad = dasha_info.get('ad_lord', '—')
        pd = dasha_info.get('pd_lord', '')
        md_end = dasha_info.get('md_end', '—')
        dasha_html = f"""
        <div class="panchanga">
          <h3>Current Dasha</h3>
          <table>
            <tr><td><b>Mahadasha</b></td><td>{md}</td><td><b>Ends</b></td><td>{md_end}</td></tr>
            <tr><td><b>Antardasha</b></td><td>{ad}</td><td><b>Pratyantar</b></td><td>{pd}</td></tr>
          </table>
        </div>"""

    return f"""<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Georgia', serif; margin: 20px; font-size: 11pt; color: #1a1a1a; }}
  h1 {{ color: #7B1E2A; font-size: 18pt; text-align: center; margin-bottom: 4px; }}
  h2 {{ color: #D4500A; font-size: 14pt; border-bottom: 2px solid #D4500A; padding-bottom: 4px; }}
  h3 {{ color: #7B1E2A; font-size: 12pt; }}
  .header {{ text-align: center; margin-bottom: 16px; color: #595959; font-size: 10pt; }}
  table {{ width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 10pt; }}
  th {{ background: #1F3864; color: white; padding: 5px 8px; text-align: left; }}
  td {{ padding: 4px 8px; border-bottom: 1px solid #e0e0e0; }}
  tr:nth-child(even) td {{ background: #F5F0EB; }}
  .panchanga {{ margin: 10px 0; padding: 10px; background: #FFFEF5; border: 1px solid #D4500A; border-radius: 4px; }}
  .two-col {{ display: flex; gap: 20px; }}
  .col {{ flex: 1; }}
  .disclaimer {{ background: #FFF3E0; padding: 8px 12px; border-left: 4px solid #FF9800;
                 font-size: 9pt; color: #555; margin-top: 16px; }}
  .footer {{ text-align: center; color: #888; font-size: 9pt; margin-top: 20px;
             border-top: 1px solid #ddd; padding-top: 8px; }}
</style>
</head><body>
<h1>ॐ — {title} · Analysis</h1>
<div class="header">LagnaMaster v3.0.0 · Heuristic Scoring Engine</div>

<div class="two-col">
  <div class="col">
    <h2>House Scores (Heuristic)</h2>
    <table>
      <tr><th>House</th><th>Score</th><th>Quality</th><th>Bar</th></tr>
      {score_rows if score_rows else "<tr><td colspan='4'>Scores not available</td></tr>"}
    </table>
    {dasha_html}
  </div>
  <div class="col">
    <h2>Active Yogas</h2>
    <table>
      <tr><th>Yoga</th><th>Strength</th><th>Description</th></tr>
      {yoga_rows if yoga_rows else "<tr><td colspan='3'>No yogas provided</td></tr>"}
    </table>
  </div>
</div>

<div class="disclaimer">
  <b>Important:</b> The house scores shown are heuristic estimates generated by a
  computational scoring engine. They do not constitute authoritative classical Jyotish
  verdicts. Classical Jyotish requires contextual, synthetic judgment by a qualified
  astrologer. These scores should be treated as directional indicators only.
</div>

<div class="footer">
  LagnaMaster · Sessions 1–160 · Sources: BPHS (PVRNR), Saravali, Phaladeepika
</div>
</body></html>"""


def export_pdf(
    chart,
    output_path: str,
    title: str = "Birth Chart",
    chart_svg: str = "",
    panchanga=None,
    house_scores: dict = None,
    yogas: list = None,
    dasha_info: dict = None,
    chart_style: str = "south",
) -> bool:
    """
    Export a 2-page PDF chart report.

    Args:
        chart: BirthChart
        output_path: output .pdf path
        title: person's name or chart title
        chart_svg: pre-generated SVG string (from north_indian_chart.py or existing)
        panchanga: Panchanga object (optional)
        house_scores: {house: score} dict (optional)
        yogas: list of yoga results (optional)
        dasha_info: dict with md_lord, ad_lord, pd_lord, md_end (optional)
        chart_style: "south" or "north"

    Returns: True if PDF written successfully

    Source: Standard Jyotish consultation deliverable format.
    """
    # Generate chart SVG if not provided
    if not chart_svg:
        try:
            if chart_style == "north":
                from src.calculations.north_indian_chart import generate_north_indian_svg
                chart_svg = generate_north_indian_svg(chart, title=title, color_scheme="color")
            else:
                from src.calculations.north_indian_chart import generate_south_indian_svg
                chart_svg = generate_south_indian_svg(chart, title=title, color_scheme="color")
        except Exception:
            chart_svg = "<p>Chart SVG not available</p>"

    page1_html = _chart_html(chart, chart_svg, panchanga, title)
    page2_html = _analysis_html(chart, house_scores, yogas, dasha_info, title)

    # Attempt weasyprint
    try:
        from weasyprint import HTML, CSS
        from weasyprint.text.fonts import FontConfiguration

        font_config = FontConfiguration()
        combined_html = page1_html.replace(
            '</body></html>',
            f'<div style="page-break-after:always"></div></body></html>'
        ) + page2_html

        HTML(string=combined_html).write_pdf(
            output_path,
            font_config=font_config,
        )
        return True

    except ImportError:
        pass  # weasyprint not available

    # Fallback: write HTML files that user can print to PDF
    html_path = output_path.replace('.pdf', '.html')
    combined = page1_html.replace(
        '</body></html>',
        '<hr style="page-break-after:always"/></body></html>'
    ) + page2_html.replace('<!DOCTYPE html>\n<html>', '').replace('</html>', '')

    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(combined)

    # Try to note fallback
    with open(output_path + '.note.txt', 'w') as f:
        f.write(f"PDF export requires weasyprint (pip install weasyprint).\n"
                f"HTML output written to: {html_path}\n"
                f"Open in browser and use File > Print > Save as PDF.")

    return False  # PDF not written, HTML fallback used


def export_html(
    chart,
    output_path: str,
    title: str = "Birth Chart",
    **kwargs,
) -> str:
    """
    Export chart as standalone HTML file (no weasyprint dependency).
    Returns the HTML string.
    """
    chart_svg = kwargs.get('chart_svg', '')
    if not chart_svg:
        try:
            from src.calculations.north_indian_chart import generate_south_indian_svg
            chart_svg = generate_south_indian_svg(chart, title=title, color_scheme="color")
        except Exception:
            chart_svg = ""

    html = _chart_html(chart, chart_svg, kwargs.get('panchanga'), title)

    if output_path:
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)

    return html
